name: Deploy Python Azure Function - notifyemailapp

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r BlobDeleteEvent/requirements.txt

      - name: Deploy to Azure Function
        uses: Azure/functions-action@v1
        with:
          app-name: 'notifyemailapp'
          package: '.'   # repo root containing BlobDeleteEvent folder
